"""
Re-exports from the utils directory.
"""

from __future__ import annotations

from opago_mica.utils.crypto import (
    ECDHKeyPair,
    Ed25519KeyPair,
    EncryptionResult,
    KeyPair,
    SignatureResult,
    VerificationResult,
    decrypt_payload,
    decrypt_payload_with_jwk,
    decrypt_payload_with_pem,
    encrypt_payload,
    encrypt_payload_with_jwk,
    encrypt_payload_with_pem,
    export_public_key_base64,
    extract_public_jwk,
    from_base64url,
    from_base64url_bytes,
    generate_base64url_nonce,
    generate_ecdh_key_pair,
    generate_ed25519_key_pair,
    generate_key_pair,
    generate_nonce,
    generate_uuid_nonce,
    hash_data,
    hash_object,
    import_public_key_base64,
    sha256_base64url,
    sha256_hex,
    sign_payload_with_jwk,
    sign_payload_with_pem,
    to_base64url,
    verify_payload_with_jwk,
    verify_payload_with_pem,
)
from opago_mica.utils.logger import (
    SENSITIVE_FIELDS,
    audit_logger,
    create_component_logger,
    create_logger,
    log_audit_event,
    logger,
)

__all__ = [
    # logger
    "SENSITIVE_FIELDS",
    "audit_logger",
    "create_component_logger",
    "create_logger",
    "log_audit_event",
    "logger",
    # crypto
    "ECDHKeyPair",
    "Ed25519KeyPair",
    "EncryptionResult",
    "KeyPair",
    "SignatureResult",
    "VerificationResult",
    "decrypt_payload",
    "decrypt_payload_with_jwk",
    "decrypt_payload_with_pem",
    "encrypt_payload",
    "encrypt_payload_with_jwk",
    "encrypt_payload_with_pem",
    "export_public_key_base64",
    "extract_public_jwk",
    "from_base64url",
    "from_base64url_bytes",
    "generate_base64url_nonce",
    "generate_ecdh_key_pair",
    "generate_ed25519_key_pair",
    "generate_key_pair",
    "generate_nonce",
    "generate_uuid_nonce",
    "hash_data",
    "hash_object",
    "import_public_key_base64",
    "sha256_base64url",
    "sha256_hex",
    "sign_payload_with_jwk",
    "sign_payload_with_pem",
    "to_base64url",
    "verify_payload_with_jwk",
    "verify_payload_with_pem",
]
