# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trisa/gds/models/v1beta1/ca.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trisa/gds/models/v1beta1/ca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!trisa/gds/models/v1beta1/ca.proto\x12\x18trisa.gds.models.v1beta1\"\xb9\x02\n\x0b\x43\x65rtificate\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x15\n\rserial_number\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x1b\n\x13signature_algorithm\x18\x04 \x01(\t\x12\x1c\n\x14public_key_algorithm\x18\x05 \x01(\t\x12/\n\x07subject\x18\x06 \x01(\x0b\x32\x1e.trisa.gds.models.v1beta1.Name\x12.\n\x06issuer\x18\x07 \x01(\x0b\x32\x1e.trisa.gds.models.v1beta1.Name\x12\x12\n\nnot_before\x18\x08 \x01(\t\x12\x11\n\tnot_after\x18\t \x01(\t\x12\x0f\n\x07revoked\x18\n \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x0b \x01(\x0c\x12\r\n\x05\x63hain\x18\x0c \x01(\x0c\"\xc7\x01\n\x04Name\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x15\n\rserial_number\x18\x02 \x01(\t\x12\x14\n\x0corganization\x18\x03 \x03(\t\x12\x1b\n\x13organizational_unit\x18\x04 \x03(\t\x12\x16\n\x0estreet_address\x18\x05 \x03(\t\x12\x10\n\x08locality\x18\x06 \x03(\t\x12\x10\n\x08province\x18\x07 \x03(\t\x12\x13\n\x0bpostal_code\x18\x08 \x03(\t\x12\x0f\n\x07\x63ountry\x18\t \x03(\tBBZ@github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1;modelsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trisa.gds.models.v1beta1.ca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/trisacrypto/trisa/pkg/trisa/gds/models/v1beta1;models'
  _globals['_CERTIFICATE']._serialized_start=64
  _globals['_CERTIFICATE']._serialized_end=377
  _globals['_NAME']._serialized_start=380
  _globals['_NAME']._serialized_end=579
# @@protoc_insertion_point(module_scope)
