# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trisa.gds.api.v1beta1 import api_pb2 as trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trisa/gds/api/v1beta1/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TRISADirectoryStub(object):
    """The TRISADirectory service specifies how TRISA clients should interact with a
    directory service to facilitate P2P transfers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lookup = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/Lookup',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupRequest.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupReply.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/Search',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchRequest.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchReply.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/Register',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterRequest.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.VerifyContact = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/VerifyContact',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactRequest.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactReply.FromString,
                _registered_method=True)
        self.Verification = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/Verification',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationRequest.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationReply.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/trisa.gds.api.v1beta1.TRISADirectory/Status',
                request_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.HealthCheck.SerializeToString,
                response_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.ServiceState.FromString,
                _registered_method=True)


class TRISADirectoryServicer(object):
    """The TRISADirectory service specifies how TRISA clients should interact with a
    directory service to facilitate P2P transfers.
    """

    def Lookup(self, request, context):
        """Interactions with the Directory Service during a TRISA transfer
        These are the primary Directory Service interactions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Registration workflow and contact verification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verification(self, request, context):
        """Supplies the entity review and TRISA verification status of a VASP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Health check and status request that mirrors the TRISAHealth service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TRISADirectoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupRequest.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupReply.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchRequest.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchReply.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterRequest.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterReply.SerializeToString,
            ),
            'VerifyContact': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyContact,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactRequest.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactReply.SerializeToString,
            ),
            'Verification': grpc.unary_unary_rpc_method_handler(
                    servicer.Verification,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationRequest.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationReply.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.HealthCheck.FromString,
                    response_serializer=trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.ServiceState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trisa.gds.api.v1beta1.TRISADirectory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trisa.gds.api.v1beta1.TRISADirectory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TRISADirectory(object):
    """The TRISADirectory service specifies how TRISA clients should interact with a
    directory service to facilitate P2P transfers.
    """

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/Lookup',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupRequest.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.LookupReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/Search',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchRequest.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.SearchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/Register',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterRequest.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/VerifyContact',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactRequest.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerifyContactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/Verification',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationRequest.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.VerificationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trisa.gds.api.v1beta1.TRISADirectory/Status',
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.HealthCheck.SerializeToString,
            trisa_dot_gds_dot_api_dot_v1beta1_dot_api__pb2.ServiceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
